mysql -e "CREATE USER '$MYSQL_USER' IDENTIFIED BY '$MYSQL_PASS'; \
REVOKE ALL PRIVILEGES,GRANT OPTION from $MYSQL_USER; \
GRANT USAGE ON *.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASS'; \
GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'%' WITH GRANT OPTION; \
FLUSH PRIVILEGES;"
